# Sever Config
spring.application.name=HeartfeltTutoringServer
server.port=8080

# eMail
spring.mail.host=smtp.163.com
spring.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/heartfelt_tutoring
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.web.resources.static-locations=classpath:/public/

# Open AI Proxy with Silicon Flow API
spring.ai.openai.base-url=https://api.siliconflow.cn/v1
spring.ai.openai.chat.options.model=Qwen/Qwen3-Omni-30B-A3B-Instruct

# Import keys.properties
spring.config.import=classpath:keys.properties
