# Sever Config
spring.application.name=HeartfeltTutoringServer
server.port=8080

# eMail
spring.mail.host=smtp.163.com
spring.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/heartfelt_tutoring
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.web.resources.static-locations=classpath:/public/

# Aliyun OSS
aliyun.oss.endpoint= oss-cn-beijing.aliyuncs.com
aliyun.oss.bucket-name=java-zhan

# Import keys.properties
spring.config.import=classpath:keys.properties

# WeChat Oauth2 Client Config
spring.security.oauth2.client.registration.wechat.scope=snsapi_login
spring.security.oauth2.client.registration.wechat.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.wechat.redirect-uri={baseUrl}/login/oauth2/code/wechat
spring.security.oauth2.client.registration.wechat.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.wechat.client-name=wechat

# WeChat Oauth2 Provider
spring.security.oauth2.client.provider.wechat.authorization-uri=https://open.weixin.qq.com/connect/qrconnect
spring.security.oauth2.client.provider.wechat.token-uri=https://api.weixin.qq.com/sns/oauth2/access_token
spring.security.oauth2.client.provider.wechat.user-info-uri=https://api.weixin.qq.com/sns/userinfo
spring.security.oauth2.client.provider.wechat.user-name-attribute=openid
