# PostgresSQL password
spring.datasource.password=

# 163 email username and password
spring.mail.username=
spring.mail.password=

# Google Oauth2 registration
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=

# GitHub Oauth2 registration
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=