# PostgresSQL password
spring.datasource.password=

# 163 email username and password
spring.mail.username=
spring.mail.password=

# Oauth2 Google and GitHub client id and secret
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=

#spring.security.oauth2.client.registration.github.client-id=Ov23liEPqqP5jOZCc4ca
#spring.security.oauth2.client.registration.github.client-secret=8170edc810d508fa09ad5e59a7ae1dbbf2d499e1

# Open AI proxy API key
spring.ai.openai.api-key=